Repository OpenMined/TenSEAL, pull requests merged in 2020-07, with the labels that each got.

#87 Fix out-of-line declaration in tensealcontext
  tenseal/tensealcontext.cpp
Labels: Type: Bug :bug:

#89 add missing header include for "optional"
  tenseal/tensealencoder.h
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
Labels: Type: Bug :bug:

#86 Scalar operations for CKKSVector
  tenseal/binding.cpp
  tenseal/tensealencoder.h
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tests/tensors/test_ckks_vector.py
Labels: Priority: 1 - Immediate :fire:, Type: New Feature :heavy_plus_sign:

#92 Different size vector operations
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tests/cpp/tensors/bfvvector_test.cpp
  tests/cpp/tensors/ckksvector_test.cpp
  tests/tensors/test_ckks_vector.py
Labels: Priority: 1 - Immediate :fire:, Type: New Feature :heavy_plus_sign:

#93 Negate operator
  tenseal/binding.cpp
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tests/tensors/test_ckks_vector.py
Labels: Type: New Feature :heavy_plus_sign:

#94 Right arithmetic operators for CKKS vector
  tenseal/binding.cpp
  tests/tensors/test_ckks_vector.py
Labels: Type: New Feature :heavy_plus_sign:

#97 Passing immutable vectors by reference
  tenseal/binding.cpp
  tenseal/tensealencoder.h
  tenseal/tensors/bfvvector.cpp
  tenseal/tensors/bfvvector.h
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
Labels: Type: Improvement :chart_with_upwards_trend:

#98 Catch transparent ct and replace with encrypted zero
  tenseal/tensors/bfvvector.cpp
  tenseal/tensors/ckksvector.cpp
  tests/tensors/test_bvf_vector.py
  tests/tensors/test_ckks_vector.py
Labels: Type: Improvement :chart_with_upwards_trend:

#99 CKKSVector Polynomial Evaluation
  tenseal/binding.cpp
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tenseal/utils/utils.h
  tests/tensors/test_ckks_vector.py
Labels: Type: New Feature :heavy_plus_sign:

#100 CKKS square and power functions
  tenseal/binding.cpp
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tests/tensors/test_ckks_vector.py
Labels: Type: New Feature :heavy_plus_sign:

#101 TensealContext serialization
  .github/workflows/tests.yml
  CMakeLists.txt
  README.md
  tenseal/__init__.py
  tenseal/binding.cpp
  tenseal/proto/CMakeLists.txt
  tenseal/proto/tensealcontext.proto
  tenseal/serialization.h
  tenseal/tensealcontext.cpp
  tenseal/tensealcontext.h
  tenseal/utils/proto.h
  tenseal/utils/scope.h
  tests/__init__.py
  tests/cpp/tensealcontext_test.cpp
  tests/test_serialization.py
  tests/utils.py
Labels: Type: New Feature :heavy_plus_sign:

#104 Update docker images
  docker-images/Dockerfile-py36
  docker-images/Dockerfile-py37
  docker-images/Dockerfile-py38
  tenseal/proto/CMakeLists.txt
Labels: Build

#109 add serialization support in tensors
  tenseal/__init__.py
  tenseal/binding.cpp
  tenseal/proto/CMakeLists.txt
  tenseal/proto/tensealcontext.proto
  tenseal/proto/tensors.proto
  tenseal/tensealcontext.cpp
  tenseal/tensealcontext.h
  tenseal/tensors/__init__.py
  tenseal/tensors/bfvvector.cpp
  tenseal/tensors/bfvvector.h
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tenseal/utils/serialization.h
  tests/cpp/tensors/bfvvector_test.cpp
  tests/cpp/tensors/ckksvector_test.cpp
  tests/tensors/test_bfv_vector.py
  tests/tensors/test_ckks_vector.py
  tests/tensors/test_serialization.py
Labels: Type: New Feature :heavy_plus_sign:

#115 Parallel encrypted-vector-plain-matrix multiplication
  tenseal/binding.cpp
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tenseal/utils/matrix_ops.h
  tenseal/utils/utils.cpp
  tenseal/utils/utils.h
  tests/tensors/test_ckks_vector.py
Labels: Type: Improvement :chart_with_upwards_trend:

#119 Better handling of transparent ct exceptions
  tenseal/tensors/bfvvector.cpp
  tenseal/tensors/ckksvector.cpp
Labels: Type: Bug :bug:

#124 Threadpool support for matrix multiplication
  .github/workflows/tests.yml
  README.md
  tenseal/__init__.py
  tenseal/binding.cpp
  tenseal/cpp/context/sealcontext.cpp
  tenseal/cpp/context/tensealcontext.cpp
  tenseal/cpp/context/tensealcontext.h
  tenseal/cpp/tensors/ckksvector.cpp
  tenseal/cpp/tensors/ckksvector.h
  tenseal/cpp/tensors/utils/matrix_ops.h
  tenseal/cpp/tensors/utils/utils.cpp
  tenseal/cpp/tensors/utils/utils.h
  tenseal/cpp/utils/BUILD
  tenseal/cpp/utils/queue.h
  tenseal/cpp/utils/threadpool.h
  tenseal/deps.bzl
  tests/cpp/BUILD
  tests/cpp/benchmarks/BUILD
  tests/cpp/benchmarks/benchmark.cpp
  tests/cpp/tensealcontext_test.cpp
  tests/cpp/tensors/ckksvector_test.cpp
  tests/python/tenseal/tensors/test_ckks_vector.py
Labels: Type: Improvement :chart_with_upwards_trend:, Type: Refactor :hammer:
