Repository OpenMined/TenSEAL, pull requests merged in 2020-05, with the labels that each got.

#37 Relinearize CKKSVector after every ct-ct multiplication
  tenseal/binding.cpp
  tenseal/tensealcontext.cpp
  tenseal/tensealcontext.h
  tenseal/tensors/ckksvector.cpp
Labels: enhancement

#42 BFV vectors relinearization after ct-ct multiplication
  .github/workflows/tests.yml
  tenseal/tensors/bfvnaivevector.cpp
  tenseal/tensors/bfvvector.cpp
Labels: enhancement

#47 CKKSVector matrix multiplciation
  requirements_dev.txt
  tenseal/binding.cpp
  tenseal/matrix_ops.h
  tenseal/tensealcontext.h
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tenseal/utils.h
  tests/tensors/test_ckks_vector.py
Labels: enhancement

#54 Windows support
  CMakeLists.txt
  README.md
Labels: build

#57 Setting global_scale in TenSEALContext
  tenseal/binding.cpp
  tenseal/tensealcontext.h
  tenseal/tensors/__init__.py
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tests/tensors/test_ckks_vector.py
  tests/tensors/test_perf.py
  tests/test_enc_dec.py
  tests/test_tensealcontext.py
Labels: API, enhancement

#55 Python publish workflow for Windows
  .github/workflows/pythonpublish-windows.yml
Labels: build

#60 Auto Relin, Rescale and ModSwitch
  CMakeLists.txt
  tenseal/binding.cpp
  tenseal/tensealcontext.cpp
  tenseal/tensealcontext.h
  tenseal/tensors/bfvvector.h
  tenseal/tensors/ckksvector.cpp
  tenseal/tensors/ckksvector.h
  tenseal/utils/context.h
  tenseal/utils/matrix_ops.h
  tenseal/utils/utils.cpp
  tenseal/utils/utils.h
  tests/tensors/test_ckks_vector.py
  tests/test_tensealcontext.py
Labels: enhancement
