Repository OpenMined/TenSEAL, pull requests merged in 2021-03, with the labels that each got.

#236 Fix broken tutorial links in README
  README.md
Labels: Type: Documentation :books:

#255 Fix typo in BFV C++ tests names
  tests/cpp/tensors/bfvvector_test.cpp
Labels: Type: Testing :test_tube:

#256 BatchEncoder single value encoding
  tenseal/cpp/context/tensealencoder.h
Labels: Type: New Feature :heavy_plus_sign:
