Repository OpenMined/TenSEAL, pull requests merged in 2021-01, with the labels that each got.

#208 Update API for matmul
  tenseal/binding.cpp
  tenseal/cpp/tensors/bfvvector.cpp
  tenseal/cpp/tensors/bfvvector.h
  tenseal/cpp/tensors/ckkstensor.cpp
  tenseal/cpp/tensors/ckkstensor.h
  tenseal/cpp/tensors/ckksvector.cpp
  tenseal/cpp/tensors/ckksvector.h
  tenseal/cpp/tensors/encrypted_tensor.h
  tenseal/cpp/tensors/encrypted_vector.h
  tenseal/tensors/ckkstensor.py
  tenseal/tensors/ckksvector.py
  tests/cpp/tensors/ckksvector_test.cpp
  tests/python/tenseal/tensors/test_ckks_tensor.py
  tests/python/tenseal/tensors/test_ckks_vector.py
Labels: API, Type: Improvement :chart_with_upwards_trend:, Type: Refactor :hammer:

#210 Symmetric encryption support
  .github/workflows/bazel_tests.yml
  .github/workflows/tests.yml
  tenseal/__init__.py
  tenseal/binding.cpp
  tenseal/cpp/context/sealcontext.cpp
  tenseal/cpp/context/tensealcontext.cpp
  tenseal/cpp/context/tensealcontext.h
  tenseal/cpp/tensors/bfvvector.cpp
  tenseal/cpp/tensors/ckkstensor.cpp
  tenseal/cpp/tensors/ckksvector.cpp
  tenseal/cpp/tensors/encrypted_tensor.h
  tenseal/cpp/tensors/encrypted_vector.h
  tenseal/cpp/utils/BUILD
  tenseal/cpp/utils/helpers.h
  tenseal/enc_context.py
  tenseal/proto/tensealcontext.proto
  tests/cpp/benchmarks/benchmark.cpp
  tests/cpp/tensealcontext_test.cpp
  tests/cpp/tensors/bfvvector_test.cpp
  tests/cpp/tensors/ckkstensor_test.cpp
  tests/cpp/tensors/ckksvector_test.cpp
  tests/python/tenseal/test_enc_dec.py
  tests/python/tenseal/test_serialization.py
  tests/python/tenseal/test_tensealcontext.py
Labels: Type: New Feature :heavy_plus_sign:

#209 Refactor: remove duplicate dot functions (plain/encrypted)
  tenseal/cpp/tensors/ckkstensor.cpp
  tenseal/cpp/tensors/ckkstensor.h
Labels: Type: Refactor :hammer:

#212 Encode/Encrypt a single double
  tenseal/cpp/tensors/ckkstensor.cpp
Labels: Type: Improvement :chart_with_upwards_trend:

#220 CKKSTensor: complete dot operation
  .gitmodules
  tenseal/cpp/tensors/ckkstensor.cpp
  tenseal/cpp/tensors/ckkstensor.h
  tests/python/tenseal/tensors/test_ckks_tensor.py
Labels: Type: Improvement :chart_with_upwards_trend:, Type: New Feature :heavy_plus_sign:

#226 CKKSVector: update replicate_first_slot
  tenseal/cpp/tensors/ckksvector.cpp
  tests/python/tenseal/tensors/test_ckks_vector.py
Labels: Type: Improvement :chart_with_upwards_trend:
